"""Full initial schema setup - Final Attempt

Revision ID: 2df14ce67b36
Revises: 82f799081a03
Create Date: 2025-06-04 16:17:44.275628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df14ce67b36'
down_revision: Union[str, None] = '82f799081a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
