"""Add category_requirements to DegreeProgram

Revision ID: 2df545ff5e4c
Revises: dede69e0b9d7
Create Date: 2025-06-04 15:56:08.869540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df545ff5e4c'
down_revision: Union[str, None] = 'dede69e0b9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
