"""Add server_default to updated_at in UserProfile

Revision ID: 7093543d1692
Revises: f5f71822810a
Create Date: 2025-06-04 15:41:11.842354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # <-- Make sure this is imported if using specific dialect types


# revision identifiers, used by Alembic.
revision: str = '7093543d1692'
down_revision: Union[str, None] = 'f5f71822810a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_profiles', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True), # Use postgresql.TIMESTAMP for PostgreSQL types
        nullable=False,
        server_default=sa.text('now()'), # <-- This adds the default for inserts
        existing_nullable=False, # Keep existing nullability
        existing_server_default=None # Indicate that there was no existing server default
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_profiles', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=None, # <-- Remove the default on downgrade
        existing_nullable=False,
        existing_server_default=sa.text('now()') # Indicate it had a default
    )
    # ### end Alembic commands ###