"""remove avatar_path column

Revision ID: 73bb0498c682
Revises: 77dc546ba078
Create Date: 2025-06-10 16:49:00.683352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bb0498c682'
down_revision: Union[str, None] = '77dc546ba078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_path')
    # ### end Alembic commands ###
