"""Add avatar_path to user_profiles

Revision ID: 77dc546ba078
Revises: a0e532d55b68
Create Date: 2025-06-10 16:43:00.343362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77dc546ba078'
down_revision: Union[str, None] = 'a0e532d55b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
