"""add user sessions table

Revision ID: 916ca59795ef
Revises: 73bb0498c682
Create Date: 2025-06-11 14:58:23.555008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916ca59795ef'
down_revision: Union[str, None] = '73bb0498c682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
