"""Add category_requirements to DegreeProgram

Revision ID: b0de02fbdf9a
Revises: 2df545ff5e4c
Create Date: 2025-06-04 15:58:23.400627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0de02fbdf9a'
down_revision: Union[str, None] = '2df545ff5e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degree_programs', sa.Column('category_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('degree_programs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('degree_programs', 'catalog_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('degree_programs', 'total_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'degree_programs', ['name'])
    op.drop_column('degree_programs', 'is_active')
    op.drop_column('degree_programs', 'updated_at')
    op.drop_column('degree_programs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degree_programs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('degree_programs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('degree_programs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'degree_programs', type_='unique')
    op.alter_column('degree_programs', 'total_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('degree_programs', 'catalog_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('degree_programs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('degree_programs', 'category_requirements')
    # ### end Alembic commands ###
