"""Add enrollment_date to AcademicInfo

Revision ID: dede69e0b9d7
Revises: 7093543d1692
Create Date: 2025-06-04 15:52:20.265302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dede69e0b9d7'
down_revision: Union[str, None] = '7093543d1692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_infos', sa.Column('enrollment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_infos', 'enrollment_date')
    # ### end Alembic commands ###
